// Which build this is. REGENERATED BY `npm run build` — the checked-in value is the safe
// one, so anything loaded straight from the repo behaves like production.
//
//   prod   what ships. No log buffer, no log switch, and nothing ever written to disk that
//          the user did not ask for by name.
//   stg    the same extension with its diagnostics on: it keeps a log and writes it to
//          Downloads after each run of the pages, which is how a site that misbehaves on
//          someone else's machine becomes something anyone can read.
//
// Two builds rather than one with a hidden switch, because "off by default" is a promise
// enforced by whoever remembers it, and a build is a promise enforced by the file.
export const ENV = 'prod';
export const DEV = false;

// Lifts the blocked-host list, for pointing the engine at a hard page while it is being
// built. Not a feature and not a setting: `npm run build:stg -- --unblock` is the only
// thing that can turn it on, the prod build REFUSES the flag outright, and every build
// re-generates this file — so it lapses the next time anyone runs a build, which is the
// only kind of "remember to turn it off again" that actually works.
export const UNBLOCK = false;
